from pydantic import BaseModel, Field

from oai import OAI, OAIConfig, ChatInput, Message, ChatOutput


class SearchQueries(BaseModel):
    """Structured output for search queries generated by the orchestrator."""
    queries: list[str] = Field(description="List of search queries to execute")


def _get_system_prompt(max_queries: int, deep_research: bool) -> str:
    base_prompt = f"""You are an expert research planner and query generation agent. Your objective is to analyze the user's prompt and break it down into a highly targeted list of search engine queries necessary to construct a comprehensive, factual answer.

Guidelines for generating queries:
1. Maximize Signal: Use specific keywords, entities, and timeframes. Avoid conversational language in the search queries (e.g., instead of "What did Apple announce recently?", use "Apple recent product announcements press release 2026").
2. Cover Blind Spots: For complex topics, ensure your queries cover different angles (e.g., if asked about a company's performance, query their official earnings report AND critical financial news analysis).
3. Iterative Context: If you are provided with previous search findings and a list of "missing information," generate queries strictly aimed at filling those specific knowledge gaps without repeating previous searches.

You must return exactly the requested JSON structure containing the array of search queries. Generate between 1 and {max_queries} queries."""

    if deep_research:
        return base_prompt + f"""

DEEP RESEARCH MODE: This is an iterative research process. You will have multiple opportunities to search (up to 3 iterations total). 

Strategy for deep research:
- Focus on the MOST IMPORTANT aspects first in this iteration
- Don't try to cover everything at once — prioritize depth over breadth
- If the topic is complex, start with foundational queries and let subsequent iterations fill in details
- Each iteration will build on previous findings, so you can refine and dig deeper as needed

Generate up to {max_queries} focused queries for this iteration."""
    else:
        return base_prompt + f"""

STANDARD MODE: This is a single-pass search. Generate queries that will best answer the user's question in one attempt.

Strategy for standard search:
- Balance breadth and depth since this is your only search opportunity
- For simple questions, 1-2 focused queries are sufficient
- For complex questions, use all {max_queries} queries to cover different angles"""


def _format_user_message(messages: list[Message], previous_context: str | None = None) -> str:
    """
    Format conversation messages into a structured prompt for the orchestrator.
    
    Args:
        messages: List of conversation messages
        previous_context: Optional context from previous search iterations
    
    Returns:
        Formatted string for the orchestrator
    """
    parts = []
    
    parts.append("=== USER REQUEST ===")
    for msg in messages:
        if msg.role == "user":
            parts.append(msg.content)
        elif msg.role == "assistant":
            parts.append(f"[Previous Assistant Response]: {msg.content}")
    
    if previous_context:
        parts.append("\n=== PREVIOUS SEARCH FINDINGS ===")
        parts.append(previous_context)
        parts.append("\n=== TASK ===")
        parts.append("Generate new search queries to fill in the missing information. Do not repeat previous searches.")
    else:
        parts.append("\n=== TASK ===")
        parts.append("Generate search queries to answer the user's request.")
    
    return "\n".join(parts)


async def orchestrate(
    client: OAI,
    messages: list[Message],
    deep_research: bool = False,
    previous_context: str | None = None,
) -> tuple[SearchQueries, ChatOutput]:
    """
    Generate search queries from conversation messages.
    
    Takes the conversation history and generates parallel search queries
    for the Tavily search agent.
    
    Args:
        client: OAI client instance
        messages: List of conversation messages
        deep_research: If True, generate up to 5 queries. If False, up to 3.
        previous_context: Optional context from previous search iterations (for deep research loops)
    
    Returns:
        Tuple of (SearchQueries, ChatOutput)
    """
    max_queries = 5 if deep_research else 3
    
    class BoundedSearchQueries(BaseModel):
        """Search queries with bounded count."""
        queries: list[str] = Field(
            description=f"List of 1 to {max_queries} search queries to execute",
            min_length=1,
            max_length=max_queries,
        )
    
    config = OAIConfig(model="gpt-5-mini", reasoning_effort="low")
    
    formatted_message = _format_user_message(messages, previous_context)
    
    input = ChatInput(
        system_prompt=_get_system_prompt(max_queries, deep_research),
        messages=[Message(role="user", content=formatted_message)],
        metadata={"deep_research": deep_research, "max_queries": max_queries},
    )
    
    result, output = await client.chat_async_structured(
        input=input,
        response_model=BoundedSearchQueries,
        config=config,
    )
    
    search_queries = SearchQueries(queries=result.queries)
    
    return search_queries, output
